name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP with extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Specify the PHP version you need
        extensions: mbstring, xml, bcmath, gd # List any PHP extensions you need

    - name: Set up Composer
      uses: composer/composer-action@v2
      with:
        composer-version: '2' # Use Composer 2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP scripts
      run: |
        php path\to\your\script.php # Replace with your PHP file path
        # You can add more commands here to run additional PHP files or scripts

    - name: Run tests
      run: composer run-script test
      # Make sure to define a "test" script in your composer.json for this to work
